
omod ACTIVE-OBJ-RESOURCE is
  ex ACTIVE-OBJECTS-CORE .    --- your base semantics

 
 
 
 
 
 
 
  ---op alt   : Requirement Requirement -> ResourceProfile      [ctor] .
  class METHODD |
    sig      : Oid,
    body     : Oid,
    Rcost : Int,
    Tcost : Int,
    requires : ResourceProfile
  .
 sort ResourceSet .
op emptyResources : -> ResourceSet .
op _:_ : ResourceSet ResourceSet -> ResourceSet [assoc comm id: emptyResources] .
 
 

  
  sorts RequestEntry ReqQueue .      --- one (caller,method,args,future)
  subsort RequestEntry < ReqQueue .      --- one (caller,method,args,future)
  op nilReq : -> ReqQueue .
  op _;_ : ReqQueue ReqQueue -> ReqQueue [assoc id: nilReq] .
  class RESOURCE-POOL | pool : ResourceSet, requests : ReqQueue .
  subsort Object < ResourceSet .
  
  
    op reqEntry : Oid Oid Args ResourceProfile Int -> RequestEntry [ctor] .
  

  
  
var PST : ProcessState .
var lv : LocalVarList .
var st : Statement .
var prp QT : ProcessPool .

    	
  vars P1 P2 : LocalVar .
  vars V1 V2 : Value .
  
  
  
vars Mtd RPool O M counter timespan OCid ECid SIG MBOD RP : Oid .
var Q : ProcessPool .
vars ReqS       : ResourceProfile .
var N : Int .
vars  ResS : ResourceSet .
vars Rss  : Oid .
var ReqQ : ReqQueue . 
var PL : ParamList .
vars LVL : LocalVarList .
vars X L : LocalVar .
vars XYY FOid : FutureOid .
var A : Args .
var S SS : Statement .
var E : Expr .
vars RP1 RP2  : ResourceProfile .
vars RS Rs : Oid .
vars T : String .
var K Fld Fld1 t I : Int .
vars AA AS2  : AttrSet .
var ResStt : ResState .
var RE : RequestEntry .
vars FSs1 : FutureState .

 
  
rl [Async-Call-Require] :
  < M : METHODD | sig : SIG, body : MBOD, Rcost : 25, Tcost : 25, requires : RP1 >    
  < O : OBJECT | id : OCid, fields : Fld, proc : { LVL | (XYY = E ! M(A)) ; S }, suspended : Q >
    < counter : COUNTER | count : N >
    < timespan : TIMESPAN | ts : t >
  
  =>
      < timespan : TIMESPAN | ts : t + 1 >
  
  < O : OBJECT | id : OCid, fields : Fld + 1 , proc : { LVL ; (XYY := fut(N)) | S }, suspended : Q >
  invoc(E, fut(N), M, A, RP1)
< fut(N) : Future | value : someInt(0), state : unresolved >
  < counter : COUNTER | count : N + 1 >
 .
 
 
  rl [Invoc] :

< SIG : SIGNATURE | params : PL >
< MBOD : METHODBODY | stmt : SS > --- < M : METHOD | sig : SIG, body : MBOD >	
  < fut(N) : Future | value : someInt(I), state : unresolved >
 < O : OBJECT | id : OCid, fields : Fld, suspended : Q >
    invoc(O, fut(N), M, A, RP1)  
        < timespan : TIMESPAN | ts : t >
    
  =>  
        < timespan : TIMESPAN | ts : t + 1 >
  
  < fut(N) : Future | value : someInt(I), state : unresolved >   
  < O : OBJECT | id : OCid, fields : Fld + 1, suspended :
  Q ; (bind(O, fut(N), < MBOD : METHODBODY | >, < SIG : SIGNATURE | > ,  A, OCid, RP1)) >  
 . 
 
 
rl [Finish-eos] :
  < O : OBJECT | id : OCid, fields : Fld, proc : { LVL | eos }, suspended : Q >
  =>
  < O : OBJECT | id : OCid, fields : Fld + 1, proc : idle, suspended : Q ; { LVL | eos } > .

 





crl [activate-singleton] :
< RP : RESOURCE-POOL | pool : ResS, requests : ReqQ >
  < O : OBJECT | id : OCid, fields : Fld, proc : idle, suspended : { LVL ; (rr :== RP1) | S } >
  => 
< RP : RESOURCE-POOL | pool : ResS , requests : ReqQ >
  < O : OBJECT | id : OCid, fields : 10001, proc : { LVL ; (rr :== RP1 ) | S }, suspended : emptyPool  >
    reserveResource(RP1)
    if containsReturn(S) and feasibleProfile(RP1, ResS) 
    .
    
    crl [activate-non-empty] :
< RP : RESOURCE-POOL | pool : ResS, requests : ReqQ >
  < O : OBJECT | id : OCid, fields : Fld, proc : idle, suspended : { LVL ; (rr :== RP1) | S } ; Q >
  => 
< RP : RESOURCE-POOL | pool : ResS , requests : ReqQ >
  < O : OBJECT | id : OCid, fields : 10001, proc : { LVL ; (rr :== RP1 ) | S }, suspended : Q  >
    reserveResource(RP1)
    if containsReturn(S) and feasibleProfile(RP1, ResS) 
    .


crl [do-reserve-or-leftt] :
  reserveResource(RP1 or RP2)
  < Rid : RESOURCE-POOL | pool : ResS, requests : ReqQ >
=>
  reserveResource(RP1)
  < Rid : RESOURCE-POOL | pool : ResS, requests : ReqQ >
if costProfile(RP1, ResS) <= costProfile(RP2, ResS) .


crl [do-reserve-or-rightt] :
  reserveResource(RP1 or RP2)
  < Rid : RESOURCE-POOL | pool : ResS, requests : ReqQ >
=>
  reserveResource(RP2)
  < Rid : RESOURCE-POOL | pool : ResS, requests : ReqQ >
if costProfile(RP1, ResS) > costProfile(RP2, ResS) .



rl [allocate-disj] :
  reserveResource(needs(TYP, N, ATTRS) or RP2)
  < timespan : TIMESPAN | ts : 3 >
  < RP : RESOURCE-POOL | pool : < Rid : RESOURCE | type  : TYP, attrs : ATTRS', state : available, ResCost : RC > : ResS, requests : ReqQ >
  	=>
  reserveResource(RP2)
  	
  < RP : RESOURCE-POOL | pool : < Rid : RESOURCE | type  : TYP, attrs : ATTRS', state : reserved > : ResS, requests : ReqQ >
 
  < timespan : TIMESPAN | ts : 5 >
  
 .
 
 
rl [allocate-conj] :
  reserveResource(needs(TYP, N, ATTRS) and RP2)
  < timespan : TIMESPAN | ts : t >
  < RP : RESOURCE-POOL | pool : < Rid : RESOURCE | type  : TYP, attrs : ATTRS', state : available, ResCost : RC > : ResS, requests : ReqQ >
  	=>
  reserveResource(RP2)
  	
  < RP : RESOURCE-POOL | pool : < Rid : RESOURCE | type  : TYP, attrs : ATTRS', state : reserved > : ResS, requests : ReqQ >
 
  < timespan : TIMESPAN | ts : t + 1 >
  
 .
rl [do-reserve-noneProfile] :
  reserveResource(noneProfile)
  
  < RP : RESOURCE-POOL | pool : < Rid : RESOURCE | type  : TYP, attrs : ATTRS', state : available, ResCost : RC > : ResS, requests : ReqQ >
  	=>
  	
  < RP : RESOURCE-POOL | pool : < Rid : RESOURCE | type  : TYP, attrs : ATTRS', state : available, ResCost : RC > : ResS, requests : ReqQ >
 .

crl [do-reserve-atom] :
  reserveResource(needs(TYP, N, ATTRS))
  < timespan : TIMESPAN | ts : t >
  < RP : RESOURCE-POOL |
      pool : (< Rid : RESOURCE | type : TYP, attrs : ATTRS', state : available, ResCost : RC > : ResS),
      requests : ReqQ >
=>
  < timespan : TIMESPAN | ts : t + 1 >
  < RP : RESOURCE-POOL |
      pool : (< Rid : RESOURCE | type : TYP, attrs : ATTRS', state : reserved > : ResS),
      requests : ReqQ >
        reserveResource(needs(TYP, N - 1, ATTRS))
      
if N > 0 .

rl [do-reserve-atom] :
  reserveResource(needs(TYP, 0, ATTRS))
  < timespan : TIMESPAN | ts : t >
  < RP : RESOURCE-POOL | pool : ResS, requests : ReqQ >
=>
  < timespan : TIMESPAN | ts : t + 1 >
  < RP : RESOURCE-POOL | pool : ResS, requests : ReqQ >
      
.








      rl [Return] :
  < fut(N) : Future | value : someInt(0), state : unresolved > 
  < O : OBJECT | id : OCid, fields : Fld, proc : { LVL ; (destiny :== fut(N)) | S ; return(I) ; SS } >
 --- < E : OBJECT | id : ECid, fields : Fld1, proc : idle, suspended : emptyPool >
  
=>
  < O : OBJECT | id : OCid, fields : Fld + 1, proc : idle  >
 --- < E : OBJECT | id : ECid, fields : Fld1, proc : idle, suspended : emptyPool >
 
  < fut(N) : Future | value : someInt(I), state : resolved >
   refresh(fut(N))
  .
    
    rl [activate-refreshed-f] : 
    refresh(fut(N))
  < fut(N) : Future | value : someInt(I), state : resolved > 
  < O : OBJECT | id : OCid, fields : Fld, proc : idle, suspended :  { LVL ; (L := fut(N)) | S  } ; Q >
  < E : OBJECT | id : ECid, fields : Fld1, proc : idle, suspended : emptyPool >
       < L : Future | value : someInt(K), state : unresolved > 
  
=>
  < O : OBJECT | id : OCid, fields : Fld + 1, proc : { LVL ; (L := fut(N)) | S  }, suspended :   Q >
  < E : OBJECT | id : ECid, fields : Fld1, proc : idle, suspended : emptyPool >
 
  < fut(N) : Future | value : someInt(I), state : resolved >
            < L : Future | value : someInt(I), state : resolved > 
  .
  
  rl [activate-refreshed-f] : 
    refresh(fut(N))
  < fut(N) : Future | value : someInt(I), state : resolved > 
  < O : OBJECT | id : OCid, fields : Fld, proc : { LVL ; (L := fut(N)) | S  }, suspended : Q >
  < E : OBJECT | id : ECid, fields : Fld1, proc : idle, suspended : emptyPool >
       < L : Future | value : someInt(K), state : unresolved > 
  
=>
  < O : OBJECT | id : OCid, fields : Fld + 1, proc : { LVL ; (L := fut(N)) | S  }, suspended :   Q >
  < E : OBJECT | id : ECid, fields : Fld1, proc : idle, suspended : emptyPool >
 
  < fut(N) : Future | value : someInt(I), state : resolved >
            < L : Future | value : someInt(I), state : resolved > 
  .
  
  
    


  
 
    rl [Async-Call-After] :
 < L : Future | value : someInt(I), state : FSs1 > 
    < O : OBJECT | id : OCid, fields : Fld, 
	proc : { LVL | (XYY = E ! M(A)after L) ; S},
    suspended : Q >
    =>
    < O : OBJECT | id : OCid, fields : Fld + 1,
    proc : {  LVL |
    if isResolvedF(< L : Future | value : someInt(I), state : FSs1 >)
	then    ( XYY = E ! M(A) ) ; S 
	else (suspend ;  XYY = E ! M(A)after L) ; S
    fi},
 	suspended : Q >  
 	 < L : Future | value : someInt(I), state : FSs1 > 	
 .



rl [suspend-priority] :
  < O : OBJECT | id : OCid, fields : Fld, proc : { LVL | suspend ; S }, suspended : Q >  
  =>
  < O : OBJECT | id : OCid, fields : Fld + 1, proc : idle, suspended : Q ; { LVL | S }  > .


var RC : Int .

op reserveResource : ResourceProfile -> Msg [ctor] .
	var C : Int .
	
op minCost : ResourceSet String AttrSet -> Int .
eq minCost(emptyResources, TYP, ATTRS) =  1000 .
eq minCost(
      < Rid : RESOURCE | type : TYP, attrs  : ATTRS', state : available, ResCost : C > : ResS,
      TYP, ATTRS
    )
  = C
   .
eq minCost(
      < Rid : RESOURCE | > : ResS,
      TYP, ATTRS
    )
  = minCost(ResS, TYP, ATTRS)
  [owise] .
  
op costProfile : ResourceProfile ResourceSet -> Int .
eq costProfile(needs(TYP, N, ATTRS), ResS) =
  N * minCost(ResS, TYP, ATTRS) .

eq costProfile(RP1 and RP2, ResS) =
  costProfile(RP1, ResS) + costProfile(RP2, ResS) .

op feasibleProfile : ResourceProfile ResourceSet -> Bool .
ceq feasibleProfile(needs(TYP, N, ATTRS) and needs(T2, K, ATTRS'), 
				< Rid : RESOURCE | type  : TYP, attrs : ATTRS', state : available, ResCost : RC > : REST) = true
if N > 0 and K > 0 .

ceq feasibleProfile(needs(TYP, N, ATTRS) or needs(T2, K, ATTRS'), 
				< Rid : RESOURCE | type  : TYP, attrs : ATTRS', state : available, ResCost : RC > : REST) = true
if N > 0 and K > 0 .


ceq feasibleProfile(needs(TYP, N, ATTRS), 
				< Rid : RESOURCE | type  : TYP, attrs : ATTRS', state : available, ResCost : RC > : REST) = true
if N > 0 .



	
 
         op reserveN     : ResourceSet ResourceProfile -> ResourceSet .
 

	 
     ---  < RP : RESOURCE-POOL | pool : (< Rid : RESOURCE | id : Rid, type : T, attrs : ATTRS, state : available, ResCost : RC > : ResS), requests : ReqQ >

vars T2            : String .
    vars A2   : AttrSet .
    vars TYP     Str    : String .
vars ATTRS ATTRS' A1 AS AR : AttrSet .
vars Rid  Rid1       : Oid .
vars REST     : ResourceSet .
var J : Int .

--- 0 resources left: you can only satisfy a need of zero
---eq feasibleProfile(needs(TYP, N, ATTRS), emptyResources) = N == 0 .

--- need 0 of anything is always OK
---eq feasibleProfile(needs(TYP, 0, ATTRS), REST) = true .

--- if the head resource matches, consume one and recur

op includesAttrs : AttrSet AttrSet -> Bool .
eq includesAttrs(emptyAttrs, AS) = true .
ceq includesAttrs((A1 ; AR), AS) = true
  if includesAttr(A1, AS) 
     and includesAttrs(AR, AS) .

op includesAttr : Attr AttrSet -> Bool .
ceq includesAttr(years(I), (years(J) ; AS)) = true
  if J >= I .
eq  includesAttr(shift(Str), (shift(Str) ; AS)) = true .
eq  includesAttr(A1, (AR ; AS)) = includesAttr(A1, AS) [owise] .
eq  includesAttr(A1, emptyAttrs) = false .


    op bind : Oid FutureOid Object Object Args Oid ResourceProfile -> ProcessState .


 
 ---< O : OBJECT | id : OCid, fields : Fld + 1, suspended :
 --- bindQ(Q, (bind(O, fut(N), < MBOD : METHODBODY | >, < SIG : SIGNATURE | > ,  dummyA, OCid)))  >
  

endom