
omod ACTIVE-OBJ-RESOURCE-TEST is
  protecting INT .    
  protecting NAT .    
  protecting QID .    
  protecting STRING .  
   ex ACTIVE-OBJ-RESOURCE .    --- your base semantics
  
  
    ops f1 f2 f3 f4 sig1  : -> FutureOid [ctor] .
    op duA : -> Args .
  eq duA = (three, four) .
   op three : -> Value .
    op four : -> Value .
    ops R  : -> Int .
    eq R = 10 .
    op pl : -> ParamList [ctor] .
  eq pl = x y .
    ops  registerPatient call : -> MethodName [ctor] .
    ops x : -> LocalVar [ctor] .

ops HOSPITAL EXPERT SURGEON : -> Oid .
ops r1 r2 r3 r4 r5 r6 r7 r8 resourcePool counter timespan : -> Oid [ctor] .
ops Hos1 m1Body m1 meth1 f1 sig1 : -> Oid [ctor] .
ops Exp1 m2Body m2 meth2 f2 sig2 : -> Oid [ctor] .
ops Sur1  : -> Oid [ctor] .
ops  assessPatientBody assessPatient f3 f4 sig3 : -> Oid [ctor] .
ops  m4Body m4 f3 f4 sig3 : -> Oid [ctor] .

  op init : -> Configuration .
  eq init =

  
  < Hos1 : OBJECT | id : HOSPITAL, fields : 10, proc : 
    { f1 | 
    	( f1 = Hos1 ! m1(duA) )
    ; 	( f2 = Exp1 ! m2(duA) after f1 ) 
    ; 	( f3 = Sur1 ! assessPatient(duA) after f2 ) 
    ; 	( f4 = Hos1 ! m4(duA) after f3 ) 
    
    ; eos },
     suspended : emptyPool >
  --- op _= _!_(_)after_ : LocalVar Expr Oid Args LocalVar -> Statement [ctor] .
  --- op _= _!_(_)after_ : Expr Expr Oid Args LocalVar -> Statement [ctor] .
  --- op _= _!_(_)after_ : Object Expr Oid Args Object -> Statement [ctor] .

     
       
   < Exp1 : OBJECT | id : EXPERT, fields : 101, proc : idle, suspended : emptyPool >
   < Sur1 : OBJECT | id : SURGEON, fields : 101, proc : idle, suspended : emptyPool >
  
 
    --- Resource Pool Intern Junior Resident Senior Resident Chief of Service
    < resourcePool : RESOURCE-POOL |
        pool :  < r1 : RESOURCE | id : r1, type  : "Intern", attrs : (years(5) ; shift("day")), state : available, ResCost : 10 >
        	 :  < r4 : RESOURCE | id : r4, type  : "Junior Resident", attrs : (years(5) ; shift("day")), state : available, ResCost : 11 >
        	 :  < r5 : RESOURCE | id : r5, type  : "Senior Resident", attrs : (years(5) ; shift("day")), state : available, ResCost : 12 >
        	 :  < r8 : RESOURCE | id : r8, type  : "Chief of Service", attrs : (years(5) ; shift("day")), state : available, ResCost : 13 >
  			 : < r2 : RESOURCE     | id : r2, type  : "Nurse", attrs : (years(5) ; shift("day")), state : available, ResCost : 14 >
  		     : < r3 : RESOURCE     | id : r3, type  : "Nurse2", attrs : (years(5) ; shift("day")), state : available, ResCost : 15 >
  		     : < r6 : RESOURCE     | id : r6, type  : "Nurse3", attrs : (years(5) ; shift("day")), state : available, ResCost : 16 >
  		     : < r7 : RESOURCE     | id : r7, type  : "Nurse4", attrs : (years(5) ; shift("day")), state : available, ResCost : 17 >
  			 
       , requests : nilReq >
   
   --- methods
   
    < m1Body : METHODBODY | stmt : suspend ; return(5) ; meos > 
   < sig1 : SIGNATURE | ret : R, name : registerPatient, params : pl > 
   < m1 : METHODD      | sig      : sig1,    body : m1Body, Rcost    : 25,    Tcost : 25,
                         requires : needs("Intern", 1, (years(5) ; shift("day")))
                         and needs("Nurse", 1, (years(5) ; shift("day"))) 
                         >
  
   < m2Body : METHODBODY | stmt : suspend ; return(15) ; meos > 
   < sig2 : SIGNATURE | ret : R, name : call, params : pl > 
   < m2 : @      | sig      : sig2,    body : m2Body, Rcost    : 25,    Tcost : 25,
                         requires : needs("Junior Resident", 1, (years(5) ; shift("day")))
                         and needs("Nurse2", 1, (years(5) ; shift("day")))
                          >
 < assessPatientBody : METHODBODY | stmt : suspend ; return(25) ; meos > 
   < sig3 : SIGNATURE | ret : R, name : call, params : pl > 
   < assessPatient : METHODD      | sig      : sig3,    body : assessPatientBody, Rcost    : 25,    Tcost : 25,
                         requires : needs("Senior Resident", 1, (years(5) ; shift("day")))
                         and needs("Nurse3", 10, (years(5) ; shift("day")))
                          >

   < m4Body : METHODBODY | stmt : suspend ; return(35) ; meos > 
   < sig3 : SIGNATURE | ret : R, name : call, params : pl > 
   < m4 : METHODD      | sig      : sig3,    body : m4Body, Rcost    : 25,    Tcost : 25,
                         requires : needs("Chief of Service", 1, (years(5) ; shift("day")))
                         or needs("Nurse3", 1, (years(5) ; shift("day")))
                          >
   
  
    < counter : COUNTER | count : 1 >
    < timespan : TIMESPAN | ts : 1 > 
    
    < f1 : Future | value : someInt(1), state : unresolved  >
    < f2 : Future | value : someInt(1), state : unresolved  >
    < f3 : Future | value : someInt(1), state : unresolved  >
    < f4 : Future | value : someInt(1), state : unresolved  >
  
    
    ---< r3 : RESOURCE     | id : r3, type  : "Doctor", attrs : (years(5) ; shift("day")), state : available, ResCost : RC >
   --- < r4 : RESOURCE     | id : r4, type  : "Nurse", attrs : emptyAttrs, state : available, ResCost : RC >
   
   
     
.

var C : Configuration .


var StateR : FutureState .
var FR : FutureOid .
    var In : Int .
endom

---red in ACTIVE-OBJ-RESOURCE-TEST : reserveN(< r1 : RESOURCE | id : r1, type  : "Doctor", attrs : (years(5) ; shift("day")), state : available, ResCost : RC >
---        	 :  < r4 : RESOURCE | id : r4, type  : "Docctor", attrs : (years(5) ; shift("day")), state : available, ResCost : RC >, needs("Doctor", 1, (years(5) ; shift("day")))
---                         and needs("Docctor", 1, (years(5) ; shift("day")))) .

---reduce in ACTIVE-OBJ-RESOURCE-CHECK : modelCheck(init, <> ~ resolvedd("f1")) . 

---reduce in ACTIVE-OBJ-RESOURCE-CHECK : modelCheck(init, resolvedd("f1")) .

---set trace on .
---reservd
---set show stats on  .
rew [500] in ACTIVE-OBJ-RESOURCE-TEST : init .
 ---< r5 : RESOURCE | id : r5, type  : "Chief", attrs : (years(5) ; shift("day")), state : S, ResCost : 120 >
--- working
---red in ACTIVE-OBJ-RESOURCE-CHECK : modelCheck(init, resolvedd(f1)) .
---red in ACTIVE-OBJ-RESOURCE-TEST : init .
---red in ACTIVE-OBJ-RESOURCE-TEST :   modelCheck(init, [] <> ~ same-res("r1", "r2")).
---search [1] init =>! < FR : Future | value : someInt(35), state : StateR  > C:Configuration .
---search [1] init =>! < r5 : RESOURCE | id : r5, type  : "Senior Resident", attrs : (years(5) ; shift("day")), state : available, ResCost : 12 > C:Configuration .
