omod REACT-SYNTAX is
  protecting INT .
  protecting QID .
  protecting BOOL .
  protecting STRING .
  protecting NAT .
pr CONFIGURATION .






 


  sorts Destiny LocalVarList after Expr LocalVar Statement Value ValueOption Fields 
  ProcessPool ProcessState Args VarSet Class FutureList Clause FutureOid FutureSet .

  subsort Class < Qid .


  subsort FutureOid < Clause .
  subsort Oid < Qid .
  subsort Oid < Expr .
  subsort ValueOption < Statement .
  subsort Destiny < FutureOid .
  subsort FutureOid < LocalVar .
  subsort Value Oid < Expr .
  subsorts  FutureOid < Oid .
  subsort ProcessState < ProcessPool .
  subsort FutureOid < FutureSet .


---ProcessState
  ops idle : -> ProcessState .
  op { _ | _ } : LocalVarList Statement -> ProcessState [ctor] .
  op singleVar : LocalVar -> VarSet [ctor] .


---ProcessPool
  ops emptyPool emptyPoolZ : -> ProcessPool .
  op _;_ : ProcessPool ProcessPool -> ProcessPool [assoc id: emptyPool] .

---Classes
  class OBJECT | id : Oid, fields : Int, proc : ProcessState, suspended : ProcessPool .
  class METHODBODY | locals : LocalVarList, stmt : Statement .
  class CLASS | name : Oid .
  class Future | value : ValueOption, state : FutureState .
  class SIGNATURE | ret : Int, name : Oid, params : ParamList, depends : DepList, requires : ResourceProfile .
  class COUNTER | count : Int .
  class RESOURCE | id    : Oid, type  : String, attrs : AttrSet, state : ResState, ResCost : Int .
  class METHOD | sig      : Oid, body     : Oid .
  class FUTMON | resolved : FutureSet .



---LocalVarList
  subsort LocalVar < LocalVarList .
  subsort LocalVar < Int .
  op emptyVarList : -> LocalVarList [ctor] .
  op _;_ : LocalVarList LocalVarList -> LocalVarList [assoc comm id: emptyVarList] .


---VarSet
  op emptyVars : -> VarSet [ctor] .
  op _;_ : VarSet VarSet -> VarSet [assoc id: emptyVars] .


  ---ParamLists
  sort ParamList .
  subsort LocalVar < ParamList .
  op emptyParams : -> ParamList [ctor] .
  op __ : LocalVar LocalVar -> ParamList [id: emptyParams] .

 

  ---ValueOption
  ops someBool : Bool -> ValueOption .  
  ops someInt  : Int  -> ValueOption .  
  ops someString : String -> ValueOption .


  ---Statements

  op _;_ : Statement Statement -> Statement [ctor assoc] .
  op _:= get(_) : LocalVar Oid -> Statement [ctor] .
  op nilStmt : -> Statement [ctor] .
  op _= _!_(_) : Object Expr Oid Args -> Statement [ctor] .
  op _= _!_(_) : LocalVar Expr Oid Args -> Statement [ctor] .
  op _= _!_(_)after_ : LocalVar Expr Oid Args Clause -> Statement [ctor] .
  op _= _!_(_)after_ : LocalVar Expr Oid Args FutureSet -> Statement [ctor] .
  op _= _._(_) : Object Expr Oid Args -> Statement [ctor] .
  op _= _._(_) : LocalVar Expr Oid Args -> Statement [ctor] .
  op _= _._(_)after_ : LocalVar Expr Oid Args Clause -> Statement [ctor] .
  op _= _._(_)after_ : LocalVar Expr Oid Args FutureSet -> Statement [ctor] .
  op await : Bool -> Statement [ctor] .
  op suspend : -> Statement [ctor] .
  op suspend3 : -> Statement [ctor] .
  ops eos meos : -> Statement [ctor] .
  op cont : FutureOid -> Statement [ctor] .
  op return : Int -> Statement [ctor] .
  op new : Oid -> Expr [ctor] .                 --- expression ‘new C’
  op _=_ : LocalVar Expr -> Statement [ctor] .
  op obj : Int -> Oid [ctor] .


  ---Futures
  sort FutureState .
  ops unresolved resolved : -> FutureState .
  op Ffresh : -> FutureOid .
  op noneFuture : -> Object [ctor] .
  op fut : Int -> FutureOid [ctor] .
  op noneF : -> FutureSet [ctor] .
  op _/\_   : FutureSet FutureSet -> FutureSet [ctor assoc comm id: noneF] .
subsort FutureSet < Clause .             --- any conjunction is also a Clause
op falseC : -> Clause [ctor] .           --- empty disjunction = false
op _\/_   : Clause Clause -> Clause [ctor assoc comm id: falseC] .


  ---Args
  op _,_ : Value Value -> Args [ctor] .
  op none : -> Args [ctor] .


  ---Messages
  op invoc : Oid FutureOid Oid Args -> Msg [ctor] .
   op refresh : FutureOid  -> Msg [ctor] . --- to fix


  ---Resources
  sort ResourceProfile .  
  op needs : String Int AttrSet -> ResourceProfile [ctor] .
  op _and_ : ResourceProfile ResourceProfile -> ResourceProfile [ctor assoc comm] .
  op _or_ : ResourceProfile ResourceProfile -> ResourceProfile [ctor assoc comm id: noneProfile] .
  op noneProfile : -> ResourceProfile .



  sort ResourceSet .
  op emptyResources : -> ResourceSet .
  op _:_ : ResourceSet ResourceSet -> ResourceSet [assoc comm id: emptyResources] .
 
  class RESOURCE-POOL | pool : ResourceSet .
  subsort Object < ResourceSet .
  
  
---Attrs for Resources  
  sort Attr .               
  sort AttrSet .            
  subsort Attr < AttrSet .  
  op emptyAttrs : -> AttrSet .
  op _;_       : AttrSet AttrSet -> AttrSet [assoc comm id: emptyAttrs] .
  op years     : Int    -> Attr [ctor] .
  op shift     : String -> Attr [ctor] .

---ResourcesState
  sort ResState .
  ops available reserved inUse unavailable locked : -> ResState [ctor] .
  
    	
---Dep
  sorts OidPair DepList .
  subsort OidPair < DepList .   
  op _._ : Oid Oid -> OidPair [ctor] .
  op nilDeps : -> DepList [ctor] .
  op _;_     : DepList DepList -> DepList [assoc id: nilDeps ctor] .

   
---ops
  op destiny : -> Destiny .
  ops rr ar : -> ResourceProfile .
  op xx : -> LocalVar [ctor] . 
  op yy : -> LocalVar [ctor] . 
  ops three four : -> Value .
  op _:==_ : ResourceProfile ResourceProfile -> LocalVar [ctor] .
  op _:==_ : LocalVar Value -> LocalVar [ctor] .
  op y : -> LocalVar [ctor] .
  op _= _ : Qid Object -> LocalVar .
  op _:=_ : FutureOid FutureOid -> LocalVar .
  op _:==_ : Destiny FutureOid -> LocalVar .



var fst : FutureState .
 var LFOid : Clause .
  
 


endom
