omod REACT-SEMANTICS is
  ex REACT-SYNTAX .    




  --- Oids / object ids
  vars O OCid RP counter : Oid .
  vars M SIG MBOD : Oid .
  var  futmon : Oid .          
  var  Rid    : Oid .          

  --- Futures and future sets
  vars L : FutureOid .
  vars Fid G : FutureOid .
  vars FSet FSett RF : FutureSet .

  --- Numbers
  vars Fld Fld1 I K N AA Ci J : Int .

  --- Locals / local-var lists
  vars  LVL LVL1 : LocalVarList .
  vars P1 P2 : LocalVar .

  --- Statements
  vars S SS S1 S2 : Statement .

  --- Pools and queues
  var  Q    : ProcessPool .

  --- Expressions / args / params / values 
  var  E  : Expr .
  var  A  : Args .
  var  PL : ParamList .
  vars V1 V2 : Value .

  --- Resource structures
  var  ResS : ResourceSet .
  vars RP1 RP2 AR1 RPf : ResourceProfile .
  vars TYP TYP' Str : String .
  vars ATTRS ATTRS' A1 AS AR : AttrSet .
  var  ResStt : ResState .

  --- Future state (for small helpers)
  var  Fi : FutureState .

    	 
  ---
  var allocSet 			: ResourceProfile .
  var PST 				: ProcessState .
  var lv 				: LocalVarList .
  var  QT 				: ProcessPool .	
  vars Mtd RPool Cl  ECid  : Oid .
  vars ReqS       		: ResourceProfile .
  vars Rss  			: Oid .
  vars X 				: LocalVar .
  vars FOid 			: FutureOid .
  vars RS Rs 			: Oid .
  vars T 				: String .
  var t D				: Int .
  vars AS2  			: AttrSet .
  var B  				: Args .
  var ResSt 			: ResState .
  
    	
    	
 








---Binds
  op bind : Oid FutureOid Object Object Args Oid -> ProcessState .
  eq bind(O, Fid, < MBOD : METHODBODY | stmt : SS >, < SIG : SIGNATURE | ret : AA, params : PL, requires : RPf >, A, OCid) = 
  { destiny ; bindParams(PL, A, Fid, RPf) | SS } .
  op bindParams : ParamList Args FutureOid ResourceProfile -> LocalVarList .
  eq bindParams(P1 P2, (V1, V2), Fid, RPf) = ( P1 :== V1 ) ; ( P2 :== V2 ) ; ( destiny :== Fid ) ; ( rr :== RPf ) ; ( ar :== noneProfile ) .
   
  eq bindParams(emptyParams, none, Fid, RPf) =
  ( destiny :== Fid ) ; ( rr :== RPf ) ; ( ar :== noneProfile ) .


---getReturn
  op getReturn : Statement -> Statement .
  eq getReturn(return(AA) ; S) = return(AA) .
  eq getReturn(S1 ; S2) = getReturn(S2) .
  eq getReturn(S) = nilStmt [owise] .


 
  op containsReturn : Statement -> Bool .
  eq containsReturn(return(I)) = true .
  ceq containsReturn(S1 ; S2) = true if containsReturn(S1) and S2 =/= eos .
  ceq containsReturn(S1 ; S2) = true if containsReturn(S2) and S2 =/= eos .
  eq containsReturn(S) = false [owise] .
 

 
  

---Thiss
  op this : -> Oid . 
  op resolveThis : Oid Oid -> Oid .
  eq resolveThis(this, O) = O  .
  eq resolveThis(E, O) = E [owise] .
  
  
 
 op atts : Oid Oid -> Int .
 eq atts(Cl, O) = 0 [owise] .   --- adjust if you have class-specific inits

 



---Rules


  
crl [Async-Call] :
  < M : METHOD | sig : SIG, body : MBOD >  
  < SIG : SIGNATURE | params : PL, requires : RP1  >  
  < O : OBJECT | id : OCid, fields : Fld, proc : { LVL | (X = E ! M(A)) ; S }, suspended : Q >
  < counter : COUNTER | count : N >  
  =>  
  < O : OBJECT | id : OCid, fields : Fld , proc : { LVL ; (X := fut(N)) | S }, suspended : Q >
  
  < fut(N) : Future | value : someInt(0), state : unresolved >
  < SIG : SIGNATURE | params : PL, requires : RP1  >
  < M : METHOD | sig : SIG, body : MBOD >  
  < counter : COUNTER | count : N + 1 >
  invoc(E, fut(N), M, A)
 if N < 100 .
 
 
rl [Invoc] :
  < SIG : SIGNATURE | params : PL >
  < MBOD : METHODBODY | stmt : SS > 
  < M    : METHOD    | sig : SIG, body : MBOD >	
  < O : OBJECT | id : OCid, fields : Fld, suspended : Q >
  invoc(O, fut(N), M, A)    
  =>    
  < O : OBJECT | id : OCid, fields : Fld , suspended : Q ;
   (bind(O, fut(N), < MBOD : METHODBODY | >, < SIG : SIGNATURE | > ,  A, OCid)) > . 
 
    
rl [activate-1] :
  < O : OBJECT | id : OCid, fields : Fld, proc : idle, suspended : { LVL ; (rr :== noneProfile) | S } ; Q >
  => 
  < O : OBJECT | id : OCid, fields : Fld, proc : { LVL | S }, suspended : Q  > .

crl [activate-2] :
  < RP : RESOURCE-POOL | pool : ResS >
  < O : OBJECT | id : OCid, fields : Fld, proc : idle, suspended : { LVL ; (rr :== RP1) ; ( ar :== AR1 ) | S } ; Q >
  => 
  < RP : RESOURCE-POOL | pool : reserveResources(feasibleProfile(RP1, ResS), ResS)   >
  < O : OBJECT | id : OCid, fields : Fld, proc : { LVL ; (rr :== RP1) ; ( ar :== AR1 ) | S }, suspended : Q  >
   if AR1 =/= noneProfile .
   
   
crl [activate-alloc] :
  < RP : RESOURCE-POOL | pool : ResS  >
  < O : OBJECT | id : OCid, fields : Fld, proc : idle, suspended : { LVL ; (rr :== RP1) ; ( ar :== noneProfile ) | S } ; Q >
  => 
  < RP : RESOURCE-POOL | pool : reserveResources(feasibleProfile(RP1, ResS), ResS)   >
  < O : OBJECT | id : OCid, fields : Fld, proc : { LVL ; (rr :== RP1) ; (ar :== feasibleProfile(RP1, ResS)) | S }, suspended : Q  >
  if RP1 =/= noneProfile .

  var Sr : Statement .
crl [Return] :
  < fut(N) : Future | value : someInt(0), state : unresolved > 
  < O : OBJECT | id : OCid, fields : Fld, proc : { LVL ; (destiny :== fut(N)) ; (rr :== RP1) | S ; return(I) ; SS } >
  < E : OBJECT | id : ECid, fields : Fld1, proc : { LVL1 ; (L := fut(N)) | Sr }, suspended : Q >
  < RP : RESOURCE-POOL | pool : ResS  >
  < L : Future | value : someInt(K), state : unresolved >
  < futmon : FUTMON | resolved : RF >
  =>
  < fut(N) : Future | value : someInt(I), state : resolved >
  < O : OBJECT | id : OCid, fields : Fld, proc : idle >
  < E : OBJECT | id : ECid, fields : Fld1, proc : { LVL1 ; (L := fut(N)) | Sr }, suspended : Q >
  < RP : RESOURCE-POOL | pool : releaseResources(RP1, ResS)  >
  < L : Future | value : someInt(I), state : resolved >
  < futmon : FUTMON | resolved : L /\ RF >
  if requirementReserved(RP1, ResS) .


rl [Async-Call-After] :
  < futmon : FUTMON | resolved : RF >
  < O : OBJECT | id : OCid, fields : Fld, 
  proc : { LVL | (X = E ! M(A)after FSet) ; S},  suspended : Q >
  =>
  < futmon : FUTMON | resolved : RF >
  < O : OBJECT | id : OCid, fields : Fld,
  proc : {  LVL |
  if clauseSatisfied(FSet, RF)
  then    ( X = E ! M(A) ) ; S 
  else (suspend ;  X = E ! M(A)after FSet) ; S
  fi},
  suspended : Q >  .
  
  rl [Sync-Call-After] :
  < futmon : FUTMON | resolved : RF >
  < O : OBJECT | id : OCid, fields : Fld, 
  proc : { LVL | (X = E . M(A)after FSet) ; S},  suspended : Q >
  =>
  < futmon : FUTMON | resolved : RF >
  < O : OBJECT | id : OCid, fields : Fld,
  proc : {  LVL |
  if clauseSatisfied(FSet, RF)
  then    ( X = E ! M(A) ) ; S 
  else (suspend ;  X = E ! M(A)after FSet) ; S
  fi},
  suspended : Q >  .


rl [suspend] :
  < O : OBJECT | id : OCid, fields : Fld, proc : { LVL | suspend ; S }, suspended : Q >  
  =>
  < O : OBJECT | id : OCid, fields : Fld, proc : idle, suspended : Q ; { LVL | S }  > .


rl [Finish-eos] :
  < O : OBJECT | id : OCid, fields : Fld, proc : { LVL | eos }, suspended : Q >
  =>
  < O : OBJECT | id : OCid, fields : Fld, proc : idle, suspended : Q ; { LVL | eos } > .


crl [Self-Sync-Call] :
  < RP  : RESOURCE-POOL | pool : ResS  >
  < M    : METHOD    | sig : SIG, body : MBOD >
  < SIG  : SIGNATURE  | params : PL, requires : RP1 >
  < MBOD : METHODBODY | stmt : SS >
  < O : OBJECT | id : OCid, fields : Fld,
        proc : { LVL ; (destiny :== fut(D)) | (X = E ! M(A)) ; S },
        suspended : Q >
  < counter : COUNTER | count : N >
=>
  < RP  : RESOURCE-POOL
       | pool : reserveResources(feasibleProfile(RP1, ResS), ResS) >
  < O : OBJECT | id : OCid, fields : Fld,
        proc :
          { LVL ; (destiny :== fut(D)) ;
            bindParams(PL, A, fut(N), RP1) ; (ar :== feasibleProfile(RP1, ResS))
          | SS ; cont(fut(D)) },                               --- cont uses f = fut(D)
        suspended : Q ; { LVL ; (destiny :== fut(D)) | (X := get(fut(N))) ; S } >
  < fut(N) : Future | value : someInt(0), state : unresolved >
  < counter : COUNTER | count : N + 1 >
if resolveThis(E, OCid) == OCid  and N < 100 .


rl [Self-Sync-Return] :
  < RP : RESOURCE-POOL | pool : ResS  >
  < O  : OBJECT | id    : OCid, fields : Fld, proc  : { (destiny :== Fid) ; LVL | cont(Fid) },
        suspended : Q ; { lv ; (ar :== AR1) | S } >
=>
  < RP : RESOURCE-POOL | pool : releaseResources(AR1, ResS)  >
  < O  : OBJECT | id    : OCid, fields : Fld, proc  : { lv | S }, suspended : Q > .

crl [Sync-Call] :
  < O : OBJECT | id : OCid, fields : Fld, proc : { LVL | (X = E . M(A)) ; S }, suspended : Q >
    < counter : COUNTER | count : N >
  
=>
  < O : OBJECT | id : OCid, fields : Fld,  proc : { LVL  | (fut(N) = E ! M(A))  ; (X := get(fut(N)))   ; S  },
        suspended : Q >
          < counter : COUNTER | count : N + 1 >
          < fut(N) : Future | value : someInt(0), state : unresolved >
        
if resolveThis(E, OCid) =/= OCid .

op initFields : Oid -> Int .

crl [New] :
  < O : OBJECT | id : OCid, fields : Fld,
      proc : { LVL | (X = new(Cl)) ; S }, suspended : Q >
  < counter : COUNTER | count : N >
=>
  < O : OBJECT | id : OCid, fields : Fld,
      proc : { LVL | (X = obj(N)) ; S }, suspended : Q >
  < obj(N) : OBJECT | id : obj(N), fields : initFields(Cl),
             proc : idle, suspended : emptyPool >
  < counter : COUNTER | count : N + 1 >
if N < 100 .


  op feasibleProfile  : ResourceProfile ResourceSet -> ResourceProfile .
  eq feasibleProfile(noneProfile, ResS) = noneProfile .
  eq feasibleProfile(needs(TYP, 0, ATTRS), ResS)  = noneProfile .
  eq feasibleProfile(RP1 and RP2, ResS) = RP1 and RP2 .
  ceq feasibleProfile(RP1 or RP2, ResS) = RP1
  	if costProfile(RP1, ResS) < costProfile(RP2, ResS) .
  ceq feasibleProfile(RP1 or RP2, ResS) = RP2
  	if costProfile(RP1, ResS) > costProfile(RP2, ResS) .


  op reserveResources : ResourceProfile ResourceSet -> ResourceSet .
  eq reserveResources(noneProfile, ResS) = ResS .
  eq reserveResources(needs(TYP, 0, ATTRS), ResS)  = ResS .
  eq reserveResources(needs(TYP, N, ATTRS), ResS)  = reserveResourcesA(needs(TYP, N, ATTRS), ResS) .
  eq reserveResources(RP1 and RP2, ResS) =
  	reserveResourcesA(RP2, reserveResources(RP1, ResS)) .

  ceq reserveResources(RP1 or RP2, ResS) = reserveResourcesA(RP1, ResS)
  	if costProfile(RP1, ResS) < costProfile(RP2, ResS) .
  ceq reserveResources(RP1 or RP2, ResS) = reserveResourcesA(RP2, ResS)
  	if costProfile(RP2, ResS) < costProfile(RP1, ResS) .
  
  op reserveResourcesA : ResourceProfile ResourceSet -> ResourceSet .
  eq reserveResourcesA(needs(TYP, s N, ATTRS),
    < Rid : RESOURCE | type : TYP, state : available > : ResS)
  = < Rid : RESOURCE | type : TYP, state : reserved >
    : reserveResources(needs(TYP, N, ATTRS), ResS) .

  eq reserveResourcesA(needs(TYP, s N, ATTRS),
    < Rid : RESOURCE | type : TYP, state : reserved > : ResS)
  = < Rid : RESOURCE | type : TYP, state : reserved >
    : reserveResources(needs(TYP, N, ATTRS), ResS) .

  op countReserved : String ResourceSet -> Int .
  eq countReserved(TYP, emptyResources) = 0 .
  eq countReserved(TYP, < Rid : RESOURCE | type : TYP, state : reserved > : ResS) =
  	1 + countReserved(TYP, ResS) .
  eq countReserved(TYP, < Rid : RESOURCE | type : TYP', state : ResStt > : ResS) =
  	countReserved(TYP, ResS) [owise] .

  op requirementReserved : ResourceProfile ResourceSet -> Bool .
  eq requirementReserved(noneProfile, ResS) = true .
  eq requirementReserved(needs(TYP, N, ATTRS), ResS) =
  	countReserved(TYP, ResS) >= N .
  eq requirementReserved(needs(TYP, I, ATTRS) and needs(TYP', K, ATTRS'), ResS) =
  	requirementReserved(needs(TYP, I, ATTRS), ResS)
  		and
  	requirementReserved(needs(TYP', K, ATTRS'), ResS) .

  eq requirementReserved(needs(TYP, I, ATTRS) or needs(TYP', K, ATTRS'), ResS) =
  	requirementReserved(needs(TYP, I, ATTRS), ResS)
  		or
  	requirementReserved(needs(TYP', K, ATTRS'), ResS) .


  op releaseResources : ResourceProfile ResourceSet -> ResourceSet .
  eq releaseResources(noneProfile, ResS) = ResS .
  ceq releaseResources(needs(TYP, N, ATTRS), < Rid : RESOURCE | type : TYP, state : reserved, id : Rid, attrs : ATTRS, ResCost : Ci > : ResS)
  	= < Rid : RESOURCE | type : TYP, state : available, id : Rid, attrs : ATTRS, ResCost : Ci >
    	: releaseResources(needs(TYP, N, ATTRS), ResS)
  if N > 0 .
  ceq releaseResources(needs(TYP, N, ATTRS), < Rid : RESOURCE | type : TYP', state : ResStt, id : Rid, attrs : ATTRS', ResCost : Ci > : ResS)
  	= < Rid : RESOURCE | type : TYP', state : ResStt, id : Rid, attrs : ATTRS', ResCost : Ci >
    	: releaseResources(needs(TYP, N, ATTRS), ResS)
  if TYP =/= TYP' or ResStt =/= reserved [owise] .
  eq releaseResources(RP1 and RP2, ResS) =
  	releaseResources(RP2, releaseResources(RP1, ResS)) .
  eq releaseResources(RP1 or RP2, ResS) =
  	if requirementReserved(RP1, ResS)
  	then releaseResources(RP1, ResS)
  	else releaseResources(RP2, ResS) fi .
  
  op _in_ : FutureOid FutureSet -> Bool .  
  eq Fid in noneF   = false .
  eq Fid in (Fid /\ FSet) = true .
  eq Fid in (G /\ FSet) = Fid in FSet [owise] .
  eq Fid in (Fid:FutureOid) = true .
  eq Fid in (G:FutureOid)   = false [owise] .
  
  

op conjSatisfied : FutureSet FutureSet -> Bool .
eq conjSatisfied(noneF, FSett)       = true .
eq conjSatisfied(Fid /\ FSet, FSett) =
  (Fid in FSett) and conjSatisfied(FSet, FSett) .

op clauseSatisfied : Clause FutureSet -> Bool .
eq clauseSatisfied(falseC, FSett)    = false .
eq clauseSatisfied(Cl \/ D, FSett)    =
  clauseSatisfied(Cl, FSett) or clauseSatisfied(D, FSett) .
eq clauseSatisfied(FSet:FutureSet, FSett) =
  conjSatisfied(FSet, FSett) [owise] .
    

  op minCost : ResourceSet String AttrSet -> Int .
  eq minCost(emptyResources, TYP, ATTRS) =  1000 .
  eq minCost(
      < Rid : RESOURCE | type : TYP, attrs  : ATTRS', state : available, ResCost : Ci > : ResS,
      TYP, ATTRS
    )
  = Ci
   .
  eq minCost(
      < Rid : RESOURCE | > : ResS,
      TYP, ATTRS
    )
  = minCost(ResS, TYP, ATTRS)
  [owise] .
  
  op costProfile : ResourceProfile ResourceSet -> Int .
  eq costProfile(needs(TYP, N, ATTRS), ResS) =
  	N * minCost(ResS, TYP, ATTRS) .
  eq costProfile(RP1 and RP2, ResS) =
  	costProfile(RP1, ResS) + costProfile(RP2, ResS) .

  op countAvailable : String ResourceSet -> Int .
  eq countAvailable(TYP, emptyResources) = 0 .
  eq countAvailable(TYP, < Rid : RESOURCE | type : TYP, state : available > : ResS) =
  	1 + countAvailable(TYP, ResS) .
  eq countAvailable(TYP, < Rid : RESOURCE | type : TYP', state : ResStt > : ResS) =
  	countAvailable(TYP, ResS) [owise] .


  op includesAttrs : AttrSet AttrSet -> Bool .
  eq includesAttrs(emptyAttrs, AS) = true .
  ceq includesAttrs((A1 ; AR), AS) = true
  if includesAttr(A1, AS) 
     and includesAttrs(AR, AS) .

  op includesAttr : Attr AttrSet -> Bool .
  ceq includesAttr(years(I), (years(J) ; AS)) = true
  if J >= I .
  eq  includesAttr(shift(Str), (shift(Str) ; AS)) = true .
  eq  includesAttr(A1, (AR ; AS)) = includesAttr(A1, AS) [owise] .
  eq  includesAttr(A1, emptyAttrs) = false .




endom
